### ISSUE TITLE
Накидывание идей и новых механик (с каждого хотя-бы одну)

### ISSUE THREAD

**Issue by maloxit** [tpgame-spbstu/Tabletop-roguelike#21]

**Comment by lyphrowny** [comment]
- баффы, расположенные на игровом поле (+2 к уроку, здоровью и проч. характеристики юнита)
- игра за различных персонажей, которые дают перманентный бафф юнитам из  одной фракции (временный бафф можно сделать и через бонусы (нож, щипцы))
- система полезных ачивок, нацеленная на закрепление механик. Полезность двусторонняя:  игрок получает дополнительный стимул использовать механику; игра поощряет выполненные ачивки бонусом, редкой картой (_side effect: возможно на игрока накладывается ожидаемое поведение, ущемляя его стиль игры_)
