### ISSUE TITLE
Разобраться с Inscription (индивидуально Александр)

### ISSUE THREAD

**Issue by maloxit** [tpgame-spbstu/Tabletop-roguelike#6]
Mожно поиграть в demo или просто посмотреть прохождение на youtube, главное разобраться в механиках.

**Comment by lyphrowny** [comment]
- было просмотрено ~полтора часа [летсплея](https://m.youtube.com/watch?v=paEF5oYCnsQ)
- заданы уточняющие вопросы [maloxit](https://github.com/maloxit)
