### ISSUE TITLE
Исправить шрифты во всем проекте

### ISSUE THREAD

**Issue by ayu-f** [tpgame-spbstu/Tabletop-roguelike#94]

**Comment by lyphrowny** [comment]
Странное поведение шрифтов при изменении угла камеры по отношению к объекту шрифта (тексту)
- [ ] устранить странное поведение
- [ ] поменять шрифт (везде, где используется)
@maloxit

**Comment by maloxit** [comment]
Ещё вроде как проблема масштабирования шрифтов: хотя шрифты и векторные при увеличении размера шрифта происходит пикселизация
