### ISSUE TITLE
Доделать отображение колоды (руки)

### ISSUE THREAD

**Issue by ayu-f** [tpgame-spbstu/Tabletop-roguelike#97]

**Comment by lyphrowny** [comment]
- [ ] вставка
- [ ] удаление
- [ ] выделение объекта руки при наведении мыши
- [ ] выделение объекта руки при одиночном нажатии клавиши мыши (различие правая \ левая?)
- [ ] _разворачивание веера при небольшом количестве карт (ряд помещается в зону видимости)_
@maloxit
